%% Script to create bash files

function script_name = cv_gspls_bash_main_job_slim_addedruntime_mult(datafile)

load(datafile);

FID = fopen([setup.analysis_folder, '/' input.name '.sh'],'w');

fprintf(FID,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' setup.analysis_folder '/$JOB_ID-output-main.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' input.name ' # Name of the job \n',...
    '#$ -m e                # This is if you want emails when jobs abort or exit \n',...
    '#$ -M ' setup.email ' # your email address \n',...
    '#$ -q ' setup.queue_name '\n',...
    '#$ -soft -l h_vmem=20 \n',...
    ' \n',...
    'datafile=' datafile '\n',...
    'export MCR_CACHE_ROOT=', setup.cache_path, ' \n',...
    setup.spls_standalone_path '/cv_gspls_standalone_Dev_2024/', setup.compilation_subpath, '/run_cv_gspls_standalone_Dev_2024.sh /opt/matlab/', setup.matlab_version, ' $datafile']);

fclose(FID);

%     '#$ -q ' setup.queue_name_master ' # This is the computer queue. Use mitnvp1 or psy0cf20. For high RAM jobs use: psy0cf20. \n',...
%     '#$ -l mem_free=2G       # This is how much memory you are requesting \n',...
%     '#$ -l h_rss=2G          # This is the absolute memory limit \n',...
%     '#$ -l h_stack=256M      # This is for matlab \n',...

script_name = [setup.analysis_folder, '/' input.name '.sh'];

system(['qsub ' setup.analysis_folder, '/' input.name '.sh']);

end