%% Script to create bash files

function dp_bash_main_job(spls_standalone_path, project_folder, project_name, queue_name, variables_for_analysis, email)

nn=1;
if ~exist([project_folder '/' project_name],'dir')
    mkdir([project_folder '/' project_name]);
    analysis_folder = [project_folder '/' project_name];
else
    while nn < 100
        if exist([project_folder '/' project_name '_' num2str(nn)],'dir')
            nn=nn+1;
        else
            mkdir([project_folder '/' project_name '_' num2str(nn)])
            analysis_folder = [project_folder '/' project_name '_' num2str(nn)];
            nn=100;
        end
    end
end

FID = fopen([analysis_folder '/' project_name '.sh'],'w');

fprintf(FID,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/$JOB_ID-output-main.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' project_name ' # Name of the job \n',...
    '#$ -M ' email ' # your email address \n',...
    '#$ -m ae                # This is if you want emails when jobs abort or exit \n',...
    '#$ -l mem_free=2G       # This is how much memory you are requesting \n',...
    '#$ -l h_rss=2G          # This is the absolute memory limit \n',...
    '#$ -l h_stack=256M      # This is for matlab \n',...
    '#$ -q ' queue_name ' # This is the computer queue. Use mitnvp1 or psy0cf20. For high RAM jobs use: psy0cf20. \n',...
    ' \n',...
    'spls_standalone_path=' spls_standalone_path '\n',...
    'analysis_folder=' analysis_folder '\n',...
    'queue_name=' queue_name '\n',...
    'variables_for_analysis=' variables_for_analysis '\n',...
    '\n',...
    spls_standalone_path '/dp_spls_standalone/for_testing/dp_spls_standalone $spls_standalone_path $analysis_folder $queue_name $variables_for_analysis']);

fclose(FID);

system(['qsub ' analysis_folder '/' project_name '.sh']);

end