%% Script to create bash files

function [output_file] = dp_bash_para(spls_toolbox_path, analysis_folder, type_analysis, vmem_req, no_jobs, max_sim_jobs, queue_name)

FID_hyper = fopen([analysis_folder '/' type_analysis '.sh'],'w');



switch type_analysis
    case 'hyperopt'
        comp_path = [spls_toolbox_path '/Hyperparameter_optimization/dp_RHO_avg_k_AR_DP/for_testing/dp_RHO_avg_k_AR_DP'];
    case 'permutation'
        comp_path = [spls_toolbox_path '/Permutation/dp_perm_testing/for_testing/dp_perm_testing'];
end

fprintf(FID_hyper,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/$JOB_ID-output-' type_analysis '.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' type_analysis ' # Name of the job \n',...
    '#$ -t 1-' num2str(no_jobs) ':1 \n',...
    '#$ -tc ' num2str(max_sim_jobs) ' \n',...
    '#$ -pe smp 5 \n',...
    '#$ -l h_vmem=' num2str(vmem_req) 'G \n',...
    '#$ -q ' queue_name ' # This is the computer queue. For high RAM jobs use: psy0cf20. \n',...
    comp_path ' $SGE_TASK_ID']);

fclose(FID_hyper);
output_file = [analysis_folder '/' type_analysis '.sh'];

end