%% Script to create bash files

function [output_file] = cv_mbspls_ICV_job_mult(analysis_folder, type_analysis, total_jobs, setup)

switch setup.cluster
    case 'SLURM'
        task_id_name = '$SLURM_ARRAY_TASK_ID'; 
    case 'SGE'
        task_id_name = '$SGE_TASK_ID'; 
end
switch type_analysis
    case 'hyperopt'
        comp_path = [setup.mbspls_standalone_path '/hyperopt_mbspls/', setup.compilation_subpath, '/run_hyperopt_mbspls.sh ', setup.matlab_path,...
            ' ' task_id_name ' ' analysis_folder ];
    case 'permutation'
        comp_path = [setup.mbspls_standalone_path '/permutation_mbspls/', setup.compilation_subpath, '/run_permutation_mbspls.sh ', setup.matlab_path,...
            ' ' task_id_name, ' ' analysis_folder ];
    case 'bootstrap'
        comp_path = [setup.mbspls_standalone_path '/bootstrap_mbspls/', setup.compilation_subpath, '/run_bootstrap_mbspls.sh ', setup.matlab_path,...
            ' ' task_id_name, ' ' analysis_folder ];
end
 
FID = fopen([analysis_folder '/' type_analysis '.sh'],'w');

switch setup.cluster
    case 'SLURM'
        fprintf(FID,['#!/bin/sh \n',...
            '\n',...
            '#SBATCH --chdir=' analysis_folder '/ \n', ...
            '#SBATCH --error=', analysis_folder, '/output-', type_analysis, '.err \n',...
            '#SBATCH --output=', analysis_folder, '/output-', type_analysis, '.log \n',...
            '#SBATCH --partition=', setup.partition, ' \n',...
            '#SBATCH --account=', setup.account, ' \n' ...
            '#SBATCH --nodes=', num2str(setup.nodes), ' \n' ...
            '#SBATCH --ntasks=1 \n', ...
            '#SBATCH --job-name=', type_analysis, ' \n',...
            '#SBATCH --array=1-', num2str(total_jobs), '%%', num2str(setup.parallel_jobs), ' \n',...
            '#SBATCH --mem=', num2str(setup.mem_request), 'GB \n', ...
            '$PMODE \n', ...
            'export MCR_CACHE_ROOT=', setup.cache_path,' \n',...
            comp_path]);
    case 'SGE'
        fprintf(FID,['#!/bin/bash \n',...
            '# \n',...
            '#$ -S /bin/bash \n',...
            '#$ -cwd \n',...
            '#$ -o ' analysis_folder '/output-' type_analysis '.txt #output directory \n',...
            '#$ -j y \n',...
            '#$ -q ', setup.partition, ' \n',...
            '#$ -N ' type_analysis ' # Name of the job \n',...
            '#$ -t 1-' num2str(total_jobs) ' \n',...
            '#$ -tc ' num2str(setup.parallel_jobs) ' \n',...
            '#$ -soft -l h_vmem=', num2str(setup.mem_request), ' \n',...
            'export MCR_CACHE_ROOT=', setup.cache_path, ' \n',...
            comp_path]);
end

fclose(FID);
output_file = [analysis_folder '/' type_analysis '.sh'];
%     '#$ -pe smp 10 \n',...

end