%% Script to create bash files

function [output_file] = dp_bash_100k(spls_standalone_path, analysis_folder, type_analysis, mem_total, max_sim_jobs, queue_name, K, tp, cu, cv)

switch type_analysis
    case 'hyperopt'
        comp_path = [spls_standalone_path '/dp_RHO_avg_100k/for_testing/dp_RHO_avg_100k'];
    case 'permutation'
        comp_path = [spls_standalone_path '/dp_perm_testing/for_testing/dp_perm_testing'];
end

FID = fopen([analysis_folder '/' type_analysis '.sh'],'w');

fprintf(FID,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/$JOB_ID-output-' type_analysis '.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' type_analysis ' # Name of the job \n',...
    '#$ -t 1-' num2str(K) ':1 \n',...
    '#$ -tc ' num2str(max_sim_jobs) ' \n',...
    '#$ -l mem_total=' num2str(mem_total) 'G \n',...
    '#$ -q ' queue_name ' # This is the computer queue. For high RAM jobs use: psy0cf20. \n',...
    'var_cu=' num2str(cu) '\n',...
    'var_cv=' num2str(cv) '\n',...
    'var_tp=' num2str(tp) '\n',...
    comp_path ' $SGE_TASK_ID $var_cu $var_cv $var_tp ' analysis_folder]);

fclose(FID);
output_file = [analysis_folder '/' type_analysis '.sh'];

end