%% Script to create bash files

function [output_file] = dp_bash_para_new(spls_standalone_path, analysis_folder, utilities_folder, type_analysis, mem_total, no_jobs, max_sim_jobs, queue_name)

switch type_analysis
    case 'hyperopt'
        comp_path = [spls_standalone_path '/dp_RHO_avg_k_AR_DP/for_testing/dp_RHO_avg_k_AR_DP'];
        add_path = [analysis_folder, ' ', utilities_folder];
    case 'permutation'
        comp_path = [spls_standalone_path '/dp_perm_testing/for_testing/dp_perm_testing'];
        add_path = analysis_folder;
end

FID_hyper = fopen([analysis_folder '/' type_analysis '.sh'],'w');

fprintf(FID_hyper,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/$JOB_ID-output-' type_analysis '.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' type_analysis ' # Name of the job \n',...
    '#$ -t 1-' num2str(no_jobs) ':1 \n',...
    '#$ -tc ' num2str(max_sim_jobs) ' \n',...
    '#$ -l mem_total=' num2str(mem_total) 'G \n',...
    '#$ -q ' queue_name ' # This is the computer queue. For high RAM jobs use: psy0cf20. \n',...
    comp_path ' $SGE_TASK_ID ' add_path]);

fclose(FID_hyper);
output_file = [analysis_folder '/' type_analysis '.sh'];

end