%% Script to create bash files

function [output_file] = dp_bash(analysis_folder, analysis_name, queue_name, script_path, script_name)

FID_hyper = fopen([analysis_folder '/' analysis_name '.sh'],'w');

fprintf(FID_hyper,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/$JOB_ID-output-' analysis_name '.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -N ' analysis_name ' # Name of the job \n',...
    '#$ -m ae                # This is if you want emails when jobs abort or exit \n',...
    '#$ -l mem_free=2G       # This is how much memory you are requesting \n',...
    '#$ -l h_rss=2G          # This is the absolute memory limit \n',...
    '#$ -l h_stack=256M      # This is for matlab \n',...
    '#$ -q ' queue_name ' # This is the computer queue. For high RAM jobs use: psy0cf20. \n',...
    'cd ' script_path ' \n',...
    '/opt/matlab/R2015a/bin/matlab -nodisplay -nojvm -nosplash -r "run(''' script_name ''')"']);

fclose(FID_hyper);
output_file = [analysis_folder '/' analysis_name '.sh'];

end