%% Script to create bash files

function [output_file] = dp_ICV_bash_job_mult(spls_standalone_path, queue_name, analysis_folder, type_analysis, total_jobs, parallel_jobs, mem_request, matlab_version, compilation_subpath, cache_path)

switch type_analysis
    case 'hyperopt'
        comp_path = [spls_standalone_path '/hyperopt/', compilation_subpath, '/run_hyperopt.sh /opt/matlab/', matlab_version, '  ',...
            '$SGE_TASK_ID ' analysis_folder ];
    case 'permutation'
        comp_path = [spls_standalone_path '/permutation/', compilation_subpath, '/run_permutation.sh /opt/matlab/', matlab_version, '  ',...
            '$SGE_TASK_ID ' analysis_folder ];
    case 'bootstrap'
        comp_path = [spls_standalone_path '/bootstrap/', compilation_subpath, '/run_bootstrap.sh /opt/matlab/', matlab_version, '  ',...
            '$SGE_TASK_ID ' analysis_folder ];
end
 % for_redistribution_files_only
FID = fopen([analysis_folder '/' type_analysis '.sh'],'w');

fprintf(FID,['#!/bin/bash \n',...
    '# \n',...
    '#$ -S /bin/bash \n',...
    '#$ -cwd \n',...
    '#$ -o ' analysis_folder '/output-' type_analysis '.txt #output directory \n',...
    '#$ -j y \n',...
    '#$ -q ', queue_name, ' \n',...
    '#$ -N ' type_analysis ' # Name of the job \n',...
    '#$ -t 1-' num2str(total_jobs) ' \n',...
    '#$ -tc ' num2str(parallel_jobs) ' \n',...
    '#$ -soft -l h_vmem=', num2str(mem_request), ' \n',...
    'export MCR_CACHE_ROOT=', cache_path, ' \n',...
    comp_path]);

fclose(FID);
output_file = [analysis_folder '/' type_analysis '.sh'];
%     '#$ -pe smp 10 \n',...

end