%% Script to create bash files
function [output_file] = dp_ICV_slurm_job_mult(spls_standalone_path, analysis_folder, type_analysis, total_jobs, ...
    mem_request, compilation_subpath, cache_path, matlab_path, partition, account, nodes)

switch type_analysis
    case 'hyperopt'
        comp_path = [spls_standalone_path '/hyperopt/', compilation_subpath, '/run_hyperopt.sh ', matlab_path, '  ',...
           '$SLURM_ARRAY_TASK_ID ' analysis_folder ];
    case 'permutation'
        comp_path = [spls_standalone_path '/permutation/', compilation_subpath, '/run_permutation.sh ', matlab_path, '  ',...
            '$SLURM_ARRAY_TASK_ID ' analysis_folder ];
    case 'bootstrap'
        comp_path = [spls_standalone_path '/bootstrap/', compilation_subpath, '/run_bootstrap.sh ', matlab_path, '  ',...
            '$SLURM_ARRAY_TASK_ID ' analysis_folder ];
end

 % for_redistribution_files_only
FID = fopen([analysis_folder '/' type_analysis '.sh'],'w');

fprintf(FID,['#!/bin/bash  \n',...
    '# \n',...
    '#SBATCH --chdir=' analysis_folder '/ #output directory \n',...
    '#SBATCH --error=' analysis_folder '/output-' type_analysis '.err #output directory \n',...
    '#SBATCH --output=' analysis_folder '/output-' type_analysis '.log #output directory  \n',...
    '#SBATCH --partition=' partition, ' \n',...
    '#SBATCH --account=', account, ' \n' ...
    '#SBATCH --nodes=', nodes, ' \n' ...
    '#SBATCH --job-name=' type_analysis ' # Name of the job \n',...
    '#SBATCH --array=1-' num2str(total_jobs) ' \n',...
    '#SBATCH --mem=' num2str(mem_request), 'GB \n',...
    'export MCR_CACHE_ROOT=', cache_path, ' \n',...
    comp_path]);

fclose(FID);
output_file = [analysis_folder '/' type_analysis '.sh'];
%     '#$ -pe smp 10 \n',...

end