%% Script to create bash files

function [output_file] = dp_slurm_parallel(spls_standalone_path, analysis_folder, type_analysis, mem_total, max_sim_jobs, queue_name, total_jobs, size_sets)

switch type_analysis
    case 'hyperopt'
        comp_path = [spls_standalone_path '/hyperopt/for_testing/hyperopt ',...
            '$SLURM_ARRAY_TASK_ID $var_size_sets ' analysis_folder ];
    case 'permutation'
        comp_path = [spls_standalone_path '/permutation/for_testing/permutation ',...
            '$SLURM_ARRAY_TASK_ID $var_size_sets ' analysis_folder ];
    case 'bootstrap'
        comp_path = [spls_standalone_path '/bootstrap/for_testing/bootstrap ',...
            '$SLURM_ARRAY_TASK_ID ' analysis_folder ];
end
 
FID = fopen([analysis_folder '/' type_analysis '.sbatch'],'w');

fprintf(FID,['#!/bin/bash -l \n',...
    '# \n',...
    '#SBATCH --job-name=' type_analysis ' # Name of the job \n',...
    '#SBATCH --array=1-' num2str(total_jobs) ' \n',...
    '#SBATCH --ntasks=1 \n',...
    '#SBATCH --output=' analysis_folder '/output-' type_analysis '_%A%a.out #output directory \n',...
    '#SBATCH --error=' analysis_folder '/error-' type_analysis '_%A%a.err #output directory \n',...
    '#SBATCH -D ./ \n',...
    'var_size_sets=' num2str(size_sets) '\n',...
    comp_path]);
%     '#$ -S /bin/bash \n',...
%     '#$ -l mem_total=' num2str(mem_total) 'G \n',...
%     '#$ -q ' queue_name ' # This is the computer queue. For high RAM jobs use: psy0cf20. \n',...
%     '#$ -tc ' num2str(max_sim_jobs) ' \n',...


fclose(FID);
output_file = [analysis_folder '/' type_analysis '.sbatch'];

end