function slurm_script = cv_mbspls_create_slurm_script(input, setup, custom_path)

ld_library_path = [setup.matlab_path, '/runtime/glnxa64:', ...
    setup.matlab_path, '/bin/glnxa64:', ...
    setup.matlab_path, '/sys/os/glnxa64', ...
    setup.matlab_path, '/extern/bin/glnxa64'];

slurm_script_name = ['SLURM_job_mbspls', input.name, '.sh'];
FID = fopen(fullfile(custom_path, slurm_script_name),'w');

fprintf(FID,['#!/bin/sh \n',...
    '\n',...
    '#SBATCH --error=', setup.analysis_folder, '/mbspls-output-main-%%j.err \n',...
    '#SBATCH --output=', setup.analysis_folder, '/mbspls-output-main-%%j.log \n',...
    '#SBATCH --partition=', setup.partition, ' \n',...
    '#SBATCH --account=', setup.account, ' \n' ...
    '#SBATCH --nodes=', num2str(setup.nodes), ' \n' ...
    '#SBATCH --ntasks=1 \n', ...
    '#SBATCH --job-name mbspls_main \n',...
    '#SBATCH --mem=10GB \n', ...
    '$PMODE \n', ...
    'export MCR_CACHE_ROOT=', setup.cache_path,' \n',...
    'export LD_LIBRARY_PATH=', ld_library_path, ' \n', ...
    'cd ', setup.analysis_folder, ' \n', ...
    setup.mbspls_standalone_path,'/', setup.compilation_subpath, '/', setup.standalone_version, ' ', setup.analysis_folder, '/', setup.date, '_', input.name, '_datafile.mat', ...
    ]);

fclose(FID);
slurm_script = [custom_path, '/SLURM_job_mbspls',input.name, '.sh'];
disp(['scp -r ', slurm_script, ' ', setup.user, '@srvcorem2:', setup.analysis_folder])
disp(['scp -r ', input.datafile , ' ', setup.user, '@srvcorem2:', setup.analysis_folder])
disp(['To start job, run:'])
disp(['sbatch ', fullfile(setup.analysis_folder, slurm_script_name)])
end
