// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// soft_threshold_cpp
arma::vec soft_threshold_cpp(const arma::vec& w, const double lambda);
RcppExport SEXP _mbspls_soft_threshold_cpp(SEXP wSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_threshold_cpp(w, lambda));
    return rcpp_result_gen;
END_RCPP
}
// soft_thresh_update_cpp
arma::mat soft_thresh_update_cpp(const arma::mat& X, const arma::mat& Y, const arma::vec& w_Y, const double lambda);
RcppExport SEXP _mbspls_soft_thresh_update_cpp(SEXP XSEXP, SEXP YSEXP, SEXP w_YSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_Y(w_YSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_thresh_update_cpp(X, Y, w_Y, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mbspls_soft_threshold_cpp", (DL_FUNC) &_mbspls_soft_threshold_cpp, 2},
    {"_mbspls_soft_thresh_update_cpp", (DL_FUNC) &_mbspls_soft_thresh_update_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mbspls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
