# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_threshold_cpp <- function(w, lambda) {
    .Call(`_mbspls_soft_threshold_cpp`, w, lambda)
}

soft_thresh_update_cpp <- function(X, Y, w_Y, lambda) {
    .Call(`_mbspls_soft_thresh_update_cpp`, X, Y, w_Y, lambda)
}

